# Generated by Django 5.1.1 on 2024-10-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_personajes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=30)),
                ('Marca', models.TextField(max_length=30)),
                ('Precio', models.IntegerField(max_length=30)),
                ('Lugar', models.TextField(max_length=20)),
                ('Imagen', models.ImageField(null=True, upload_to='autos')),
            ],
        ),
        migrations.DeleteModel(
            name='Personajes',
        ),
    ]
