# Generated by Django 5.1.1 on 2024-10-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_vehiculos_delete_personajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='Precio',
            field=models.IntegerField(),
        ),
    ]
